### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by raquel-ucl** [UCL/UKCORDEX-plot-explorer#14]
Not sure how these work on React, but would be nice to have some.

**Comment by raquelalegre** [comment]
There is [one test](https://github.com/UCL/UKCORDEX-plot-explorer-dev/blob/development/src/App.test.tsx) that gets run in the GH Actions workflows, but sadly budget didn't allow for adding any more in-depth testing. It just checked the website was deployed and contains the expected text for the title.

Tests can get run locally with:

```
npm ci 
```
