### ISSUE TITLE
Allow users to download search results

### ISSUE THREAD

**Issue by raquel-ucl** [UCL/UKCORDEX-plot-explorer#18]
@clairbarnes do you think this would be a download of the PNGs, a PDF version of it, or a small report built from the selectiong that explain the variables and what the plot shows?

**Comment by acholyn** [comment]
Possible solutions:

- Using client-side `a href` tag which finds the file/s ([example here](https://stackoverflow.com/a/61571848)). This seems to work fine with singles. 
     Will look into using `onClick` to implement nesting with this method for multiple downloads.
- Using JSZip for zipping files, [some](https://stackoverflow.com/questions/52882703/how-to-implement-jszip-in-react-js) of the solutions involve using `"blob"`[s](https://javascript.plainenglish.io/how-to-create-download-and-upload-files-in-react-apps-80893da4247a)
- Using [Filestack](https://blog.filestack.com/tutorials/generate-a-zip-file-with-filestack-and-react/), which has a react package and involves querying their API. Downside is registration

**Comment by acholyn** [comment]
> 

A more react-specific [solution](https://stackoverflow.com/questions/57056741/how-to-download-image-in-reactjs/57057809)

**Comment by acholyn** [comment]
Trying to use [filesaver](https://stackoverflow.com/a/63439452) and `onClick` but there appear to be problems passing the state info between components. Will attempt to use [`useContext`](https://reactjs.org/docs/hooks-reference.html#usecontext) as seen in this [example](https://www.digitalocean.com/community/tutorials/how-to-share-state-across-react-components-with-context)

**Comment by acholyn** [comment]
Have set it up as an asynchronous process which checks if the file exists in the GH repo and fetches the image/file if it does. If it does not, a warning is created. 
As the files are fetched from another repo to be viewed and passed to the download buttons, GH has encrypted the filenames, which is something to be rectified when downloading.

- [x] fix filename encryption for downloads

**Comment by acholyn** [comment]
Closed by https://github.com/UCL/UKCORDEX-plot-explorer-dev/pull/28
