### ISSUE TITLE
Move option dicts to json files

### ISSUE THREAD

**Issue by raquel-ucl** [UCL/UKCORDEX-plot-explorer#23]
Specially for the `plotvars`, as this is likely to become a very large dict of around 60 elements.

**Comment by raquelalegre** [comment]
We also need this for the content of the help and about pages.

**Comment by acholyn** [comment]
React-select is very picky about what keywords it actually recognises unless within `options`. The options were moved into another file where they can be fairly easily updated but must adhere to the structure.
