### ISSUE TITLE
Style index acronyms in plotvar dropdown

### ISSUE THREAD

**Issue by raquelalegre** [UCL/UKCORDEX-plot-explorer#31]
At the moment they show like "tas - Near Surface Air Temperature". It'd be nice the option just reads "Near-Surface Air Temperature" and it's preceded by a styled tag that reads "tas". The tag can be styled following the react-select docs on "Custom Styles: https://react-select.com/home#custom-styles

**Comment by acholyn** [comment]
This has been done by splitting up the labels into two sections and giving the front section classes that can be styled. This can also be done with the section headings if desired.
This should also be compatible if code is streamlined to read from files, though depending on how streamlined the code is, the label colours may not have the same variety.
