### ISSUE TITLE
Add resolution option

### ISSUE THREAD

**Issue by raquelalegre** [UCL/UKCORDEX-plot-explorer#39]
Users must be able to choose between two different resolutions. If dropdowns don't fit in one row, we can distribute in two rows like so:
1. Region, Season and Period
2. Plot var and plot type.

**Comment by raquelalegre** [comment]
Reopening as we got more details:

- [x] Dropdown should be called "spatial aggregation"
- [x] Options are: 12km grid, country, administrative region, or river basin.
- [x] When making screen narrower, move 5 dropdowns into 2 rows.

**Comment by acholyn** [comment]
Fixed in https://github.com/UCL/UKCORDEX-plot-explorer-dev/pull/10
