### ISSUE TITLE
Improve styling

### ISSUE THREAD

**Issue by raquelalegre** [UCL/UKCORDEX-plot-explorer#40]
This includes:
- [x] removing current margins that react-bootstrap is imposing (e.g. `<Container fluid>`)
- [x] investigate why dropdowns' font size is not updating when modifying the size of the viewport
- [x] adding styling to season labels like the one in the plot var dropdown

**Comment by acholyn** [comment]
Fixed in https://github.com/UCL/UKCORDEX-plot-explorer-dev/pull/12 and https://github.com/UCL/UKCORDEX-plot-explorer-dev/pull/15
