### ISSUE TITLE
"Save plots" button should only show when there are plots being shown

### ISSUE THREAD

**Issue by raquelalegre** [UCL/UKCORDEX-plot-explorer#42]
Currently it shows as soon as there's an option chosen in the plot type dropdown. This is confusing as it looks like you can save a plot, but none are being shown yet. Some users might not choose every options in order from left to right when they are using the explorer.

**Comment by acholyn** [comment]
Fixed in https://github.com/UCL/UKCORDEX-plot-explorer-dev/pull/16
