### ISSUE TITLE
Spatial agg button should allow more than one choice

### ISSUE THREAD

**Issue by raquelalegre** [UCL/UKCORDEX-plot-explorer#43]
At the moment it only allows for one choice. See below:

<img width="320" alt="spatial_agg" src="https://user-images.githubusercontent.com/10402246/152412886-ebe8a5dd-7250-4ca2-9b73-e22349c7a9bf.png">

It should behave like the other buttons and allow for several choices. I think the `react-select` option `isMulti` might fix it?

**Comment by acholyn** [comment]
Fixed in https://github.com/UCL/UKCORDEX-plot-explorer-dev/pull/10
