### ISSUE TITLE
Figure out where to store data and plots

### ISSUE THREAD

**Issue by acholyn** [UCL/UKCORDEX-plot-explorer#44]
We could use binder to connect to a repo with data for users to access. 
As we'll have 200k+ plots, we need to figure out where to store these as cloning the repo will take a lot of time and not always be helpful - this then leads to the question of how to access the plots if they are stored on another service.

**Comment by raquelalegre** [comment]
We'll be using for now https://github.com/UCL/UKCORDEX-plot-explorer-data
