### ISSUE TITLE
Fix resolution dropdown behaviour

### ISSUE THREAD

**Issue by raquelalegre** [UCL/UKCORDEX-plot-explorer#51]
Something odd is happening with the resolution dropdown.

To reproduce one of this:

1. Choose one option in each dropdown, with the resolution being 12 km.
1. Add a second resolution
1. Try to add a third resolution

Step 3 can't be completed because no more resolutions show, but they should.

To reproduce another one:

1. Choose one option in each dropdown, with the resolution not being 12 km
1. Add a second resolution

Step 2 shows only one option remaining (12 km) when it should show more

**Comment by acholyn** [comment]
Closed by https://github.com/UCL/UKCORDEX-plot-explorer-dev/commit/98fbc4e91786ddbdfca80a08d5a8f9fc21a56b95
